server:
  port: 8082

spring:
  application:
    name: product-catalog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_catalog_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      productServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productServiceRetry:
        maxAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      productServiceTL:
        timeoutDuration: 4s
