server:
  port: 8082

spring:
  application:
    name: product-catalog-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    

