spring:
  application:
    name: product-catalog-service
  config:
    import: configserver:http://localhost:8088
  cloud:
    config:
      name: product-catalog-service
      profile: default
      label: main
