server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product_catalog_db

  application:
    name: product-catalog-service

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.product_catalog_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 2s
