server:
  port: 8082

spring:
  application:
    name: product-catalog-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb

management:
  endpoints:
    web:
      exposure:
        include: "*"
