server:
  port: 8082

spring:
  application:
    name: product-catalog-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    
messages:
  product-created: Product created successfully
  product-fetched: Product fetched successfully
  product-updated: Product updated successfully
  product-deleted: Product deleted successfully
  product-partially-updated: Product partially updated successfully
  product-filtered: Filtered products fetched successfully
  product-not-found: Product not found with given ID
