server:
  port: 8082

spring:
  application:
    name: product-catalog-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    
messages:
  productCreated: "Product created successfully"
  productFetched: "Product fetched successfully"
  productUpdated: "Product updated successfully"
  productDeleted: "Product deleted successfully"
  productPartiallyUpdated: "Product partially updated successfully"
  productFiltered: "Filtered products fetched successfully"
  productNotFound: "Product not found with ID: "
